 /******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic_sensor.h
 *
 * Description: Header file for the Ultrasonic Sensor driver
 *
 * Author: Kerollos Wagih
 *
 *******************************************************************************/

#ifndef ULTRASONIC_SENSOR_H_
#define ULTRASONIC_SENSOR_H_

/*******************************************************************************
 *                                 INCLUDES                                    *
 *******************************************************************************/

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

/* Configure ultrasonic sensor trigger (port and pin) */
#define ULTRASONIC_SENSOR_TRIGGER_PORT_ID		PORTD_ID
#define ULTRASONIC_SENSOR_TRIGGER_PIN_ID		PIN7_ID

/* Any value greater than 5 for initially Buzzer off */
#define DISTANCE_INITIAL_VALUE		20

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * Function responsible for:
 * 1. Initializing the ICU driver as required.
 * 2. Set up the ICU callback function.
 * 3. Set the direction for the trigger pin as output through the GPIO driver.
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Function responsible for sending the trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 * Function responsible for:
 * 1. Sending the trigger pulse by using the Ultrasonic_Trigger function.
 * 2. Starting the measurement process via the ICU driver.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 * This is the callback function called by the ICU driver.
 * Function responsible for calculating the high time (pulse time) generated by
 * the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_SENSOR_H_ */
