/******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic_sensor.c
 *
 * Description: Source file for the Ultrasonic Sensor driver
 *
 * Author: Kerollos Wagih
 *
 *******************************************************************************/

/*******************************************************************************
 *                                 INCLUDES                                    *
 *******************************************************************************/

#include "ultrasonic_sensor.h"
#include "icu.h"
#include "gpio.h"
#include <util\delay.h>

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

/* Create configuration structure for ICU driver */
ICU_ConfigType ICU_Configurations = {F_CPU_8,RAISING};


/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description :
 * Function responsible for:
 * 1. Initializing the ICU driver as required.
 * 2. Set up the ICU callback function.
 * 3. Set the direction for the trigger pin as output through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	/* Initialize the ICU driver as required */
	ICU_init(&ICU_Configurations);

	/* Set up the ICU callback function */
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	/* Set the direction for the trigger pin as output through the GPIO driver */
	GPIO_setupPinDirection(ULTRASONIC_SENSOR_TRIGGER_PORT_ID, ULTRASONIC_SENSOR_TRIGGER_PIN_ID, PIN_OUTPUT);
}

/*
 * Description :
 * Function responsible for sending the trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(ULTRASONIC_SENSOR_TRIGGER_PORT_ID, ULTRASONIC_SENSOR_TRIGGER_PIN_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_SENSOR_TRIGGER_PORT_ID, ULTRASONIC_SENSOR_TRIGGER_PIN_ID, LOGIC_LOW);
}

/*
 * Description :
 * Function responsible for:
 * 1. Sending the trigger pulse by using the Ultrasonic_Trigger function.
 * 2. Starting the measurement process via the ICU driver.
 */
uint16 Ultrasonic_readDistance(void)
{
	static uint16 distance = DISTANCE_INITIAL_VALUE;

	/* Send the trigger pulse by using the Ultrasonic_Trigger function */
	if (g_edgeCount == 0)
	{
		Ultrasonic_Trigger();
	}
	else if (g_edgeCount == 2)
	{
		g_edgeCount = 0;

		/* Calculate the distance */
		distance = (uint16)((g_timeHigh * (17.0/2000) ) + 1);

		/* For the following sensor reading */
		Ultrasonic_init();

		return distance;
	}

	/* Return the same distance if it is not change */
	return distance;
}

/*
 * Description :
 * This is the callback function called by the ICU driver.
 * Function responsible for calculating the high time (pulse time) generated by
 * the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	if (g_edgeCount < 2)
	{
		g_edgeCount++;
	}

	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		ICU_clearTimerValue();

		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if (g_edgeCount == 2)
	{
		/* Get the High time */
		g_timeHigh = ICU_getInputCaptureValue();

		/* Disable ICU Driver */
		ICU_deInit();
	}
}
